spring:
  # Development Database
  datasource:
    url: jdbc:postgresql://localhost:5432/kong_ai_books_dev
    username: postgres
    password: password
  
  # JPA Development Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  # Redis Development
  data:
    redis:
      host: localhost
      port: 6379
  
  # Hot Reload
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Development Logging
logging:
  level:
    com.kong.aibooks: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development AI Settings
app:
  ai:
    enabled: true
    debug: true
    mock-responses: false